### ISSUE TITLE
Add event ID

### ISSUE THREAD

**Issue by Chilipp** [eileen-kuehn/sorse-data-filter#2]
As far as I remember, each submission get's a unique ID in Indico, right? Can we add this to the YAML front-matter and include it in the generated markdown? I.e. something like `event-{{ eventID }}.md`?

**Comment by eileen-kuehn** [comment]
@Chilipp, yes, we can do so. However, we should first ensure that we really use Indico for registration because the [website currently tells registration happens via Google Forms](https://sorse.github.io/faq/howto/attendance). Is this outdated information?

Another thing we should consider is that one markdown might reference several indico event ids. The id that is currently used in ``event-{{ id }}.md`` is the abstract id and the other ids will relate to generated indico events depending on the number of planned deliveries.

Further, I currently still hesitate on the timings:

1. Abstract is accepted and information could already be advertised on the website
2. Scheduling process takes place (we still do not know how many events we need to create)
3. Event dates and times are decided and we can create all the indico events -> at the latest, information will get available on the website now

Do you now, how we will do this? If we don't publish to the website until 3) is done, then we could already generate the Indico events and could provide the proper information directly in the generated markdown. Otherwise we would have to supplement information that are already available on the website.

**Comment by Chilipp** [comment]
I see, thanks @eileen-kuehn. I would use the abstract-ID for this then.

Concerning the registration url in #1: I'd follow your suggestion and already publish the event on the website when it has been accepted. We update it later via PR with the dates and registration urls, independent of indico.

And yes, we'll use indico for the participant registration. Nobody opposed that idea and it's preferable over Google. We need to update the privacy policy to reflect that.

**Comment by Chilipp** [comment]
@eileen-kuehn just because I did not yet see it in the template: Could you also add the abstractID to the yaml frontmatter of the .md file?

**Comment by Chilipp** [comment]
closing this as it is sufficient to have the filenames (see #17)
